### ISSUE TITLE
Вознаграждения

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#16]
Модель вознаграждений включает себя:
- кому: аккаунт, к которому привязывается вознаграждение;
- за что: операция, за которую начисляется вознаграждение;
- расчёт: заданное администратором правило расчёта вознаграждения;
- сколько: расчитанный бонус;
- статус: своя статусная модель состояний, с обязательным сохранением истории.
- перерасчёт (на будущее): прозрачная ссылка на новое вознаграждение, заменяющее старое (по какой-то причине).

**Comment by pozitronik** [comment]
Задача не выполнена. Готов только костяк, а по самой задаче ещё пилить и пилить.

**Comment by pozitronik** [comment]
Сначала понятия:
**«Продукт»** — товар или услуга, с которым совершается операция. Технически это может быть любой объект в системе.
**«Операция»** — действие, инициирующее вознаграждения (именно во множественном числе, см. далее). Один продукт может иметь произвольное количество операций, при необходимости.
**«Вознаграждение»** — конфигурируемый объект, содержащий весь объём данных и правил, требуемых для «превращения» исходных данных в цифру на счету. Для простоты можно воспринимать как «чёрный ящик», на вход которому подаётся вся информация (кто, что, когда), на выходе получается сумма бонусов. Что внутри — внешний наблюдатель не знает, но может запросить информацию о текущем состоянии.

Одна операция может (но не обязана) генерировать несколько вознаграждений, каждое из которых будет «включаться» только при выполнении заданного им правила. Например:

```
(Продукт)Сим-карта=>(Операция)продажа:
[
  (Вознаграждение){Начисляем продавцу X баллов. (продавец подозревается во фроде => замораживаем X баллов до проверки)},//«подозреваемый» продавец будет видеть баллы на счету, но не сможет их вывести сразу же 
  (Вознаграждение){Ожидаем активации карты в сети две недели:(нет активации -> послать сигнал о возможном фроде)|(есть активация -> начислить продавцу Y баллов)},//запрос статуса по данному вознаграждению вернёт "Ожидается"
  (Вознаграждение){Ожидаем внешней проверки на ФРОД:(ФРОД -> снимаем с продавца X баллов)}//вознаграждение может быть отрицательным
]
```

Логика по примеру, описанному выше, будет задаваться в некоем конфигураторе, пока не очень понятно, как это будет выглядеть. Предполагаю, что на первом этапе это будет чисто текстовый конфиг (и настройка будет частью разработки), затем появится визуальная надстройка (и настройка уйдёт в администрирование).

У продавца/администратора будут доступны визуальные интерфейсы для просмотра всей цепочки событий по доступным им областям. Например, продавец, зарегистрировавший продажу симки, тут же увидит у себя запись о начислении, а если это начисление будет заморожено — информацию о том, когда ожидается разморозка. Ближайший аналог — карта списаний/поступлений в онлайн-банкинге.

Администратор же будет видеть более развёрнутую сводку, включающую в себя всю входную информацию по всем действиям всех акторов (продавцов, менеджеров, дилеров), всю цепочку произошедших обработок по каждому действию, все правила, по которым обработки происходили, и все возможные обработки, которые, скажем, ждут срабатывания внешних триггеров.

**Comment by STyutin** [comment]
обсудили с бизнесом механики работы
На встрече обсудили основные способы начисления бонусов.
1. Фикс+Фикс
Первый фикс начисляется после подтверждения продажи в течение 48 часов (кроме федеральных каналов, Почта России может достигать до 30 дней)
Второй фикс начисляется после проверки на качество  в течение 15-30 дней в зависимости от проданной услуги
2. Фикс+% от Revenue
Первый фикс начисляется после подтверждения продажи в течение 48 часов (кроме федеральных каналов, Почта России может достигать до 30 дней)
% от Revenue начисляется после проверки на качество  в течение 15-30 дней в зависимости от проданной услуги
 
Плановую мотивацию выносим на развитие в конец бэк-лога доработок.
Условия выплаты должны быть настроечными параметрами.
 
Регистрация у сотрудников без доступа к веб или МП должна проходить через ТС по аналогии с самостоятельной регистрации сотрудника (для ТС нужен функционал регистрации сотрудников).
Подтверждение продажи у части сотрудников в альтернативе и в Почте России через USSD запросы.
 
Во вложении правила по проверке на подтверждение продажи и на качество.

**Comment by pozitronik** [comment]
Продажа симки:
1. Продавец указывает номер продаваемой симки. Проводится базовая валидация (это телефонный номер), продажа регистрируется.
2. Для зарегистрированной продажи возвращаются **_гипотетические_** вознаграждения, которые будут начислены за эту продажу.
3. По событию `self::EVENT_SELL` запускаются проверки: а) мог ли данный продавец продать эту карту; б) была ли карта продана; в) была ли карта активирована.
