### ISSUE TITLE
Авторизация для модуля картика

### ISSUE THREAD

**Issue by s1lver** [cusodede/dpl#195]
Модуль экспорта картика `gridview`, по умолчанию, позволяет обращаться к нему не авторизованным пользователям. Необходимо добавить в конфигурацию авторизацию для модуля.

**Comment by pozitronik** [comment]
Для других модулей, в которых есть свои контроллеры, - аналогично. Прописать логику доступов, добавить в конфиг алиасы каталогов контроллеров, чтобы они появились при настройке доступов.

**Comment by s1lver** [comment]
Добавлены правила для модулей:
- references
- exceptions
- db
- filestorage

Удален дублирующий функционал модуля db-mon, сделан PR для пакета (https://github.com/pozitronik/yii2-dbmon/pull/3)
