### ISSUE TITLE
Сохранение информации о событии регистрации договора

### ISSUE THREAD

**Issue by s1lver** [cusodede/dpl#230]
- слушаем событие регистрации договора
- получаем информацию по договору
- сохраняем полученную информацию в справочник "Договор"
- кидаем задание на валидацию в очередь

**Comment by pozitronik** [comment]
1. Не совсем справочник. Просто таблица с данными, а то справочниками у нас называются отдельные сущности, отнаследованные от Reference.
2. Задание валидации УЖЕ крутится в очереди и ждёт, пока эта инфа появится.

Выношу из чата (и из собственной головы) алгоритм работы наших проверок:

1. К нам прилетает с фронта запрос "пользователь X сделал продажу тарифа Y". Мы проверяем, подвязано ли для этой комбинации условий (тариф, дилер пользователя, тт пользователя, etc) какое-то правило. Если да, то:
2. Смотрим, какие шаги на это правило подвязаны. Шаг — это этап, содержащий набор проверок, при выполнении которых этап считается выполненным. За выполнение шага мы начисляем бонус.
Проверкой может быть что угодно, любое условие. Каждая проверка реализуется отдельным классом, за который можно убрать любую логику.
Какие проверки к какому шагу привязывать — решает администратор. Например, шаг "начислить 50 бонусов за подтверждение продажи" с единственной проверкой "получить подтверждение регистрации договора" и шаг "начислить 500 бонусов за 1000 минут голосового трафика" с проверками "симка не ушла в колцентр сбербанка" + "1000 минут за месяц выговорено".
3. Одной из таких проверок будет "Получить подтверждение регистрации договора". Ради неё мы завязываемся на получение этих подтверждений из DOL.

Итак, к нам прилетает событие о подтверждении регистрации договора. При этом "прилетает" не обязательно означает какой-то внешний пуш, так мы обобщаем факт принятия этой инфы.
Допустим, это событие приносит с собой всю необходимую нам информацию (если нет — мы знаем, как её получить, пока не важно). Мы эту инфу себе запоминаем в БД.

Когда проверка дёргается первый раз, то она смотрит в нашей БД, пришло ли подтверждение. Очевидно, что нет (все проверки запускаются по факту сообщения о продаже), поэтому проверка уходит в очередь. Время от времени она всплывает из очереди, смотрит в таблицу, и так, до тех пор пока
а) подтверждение не появится => тогда проверка сообщает "ок";
б) не истечёт заранее заданный таймаут => тогда проверка сообщает "не ок", шаг считается проваленным, и все ассоциированные с ним проверки также стопорятся и вылетают из очереди;
в) не прилетит сигнал "шаг стопорнулся" (другой проваленной проверкой или вручную пользователем). Проверка также вылетает из очереди.
