### ISSUE TITLE
Передрать шкурку у ppl

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#26]
^_^

**Comment by pozitronik** [comment]
1) Найти все использования glyphicons в компонентах, сделать через isBS().
2) В vendor/pozitronik/yii2-references/src/widgets - js/вью написаны на bs3, добавить bs4.

**Comment by pepebotika69** [comment]
1. пропали кнопки для редактирования в подпунктах Прототипирование (pozitronilk сказал что это ок, если так, то как редактировать?)
2. Если в под пунктах Прототипирование нажать "Новая запись", то:
- ReferenceSelectWidget неправильно загружается
- левое меню меняет свой маштаб и остается таким
- хедер открыпляется от топа и перестает работать
- если валидация не прошла, то штрифт информирующий об этом очень маленький
![Screenshot from 2021-05-25 15-14-23](https://user-images.githubusercontent.com/14938095/119496315-0bfa4200-bd6c-11eb-854f-52558e547036.png)
![Screenshot from 2021-05-25 15-16-32](https://user-images.githubusercontent.com/14938095/119496546-44018500-bd6c-11eb-9aad-9e4474890518.png)
3. Думаю это не очень важно, но стрелочки в заголовках таблицы не появляются когда сортируем по колонкам
4.

**Comment by alxlapin** [comment]
П. 3 https://github.com/cusodede/bc/commit/0f5ada36ed137d3ccf9749f8b5ec26b89a051b7f

**Comment by pozitronik** [comment]
П.п 1 и 2 исправлены: в проектных вьюхах использовались дефолтные хелперы и виджеты, я заменил их на bootstrap4.

**Comment by pozitronik** [comment]
П. 4 исправлен.

По выпиливанию кнопки - да, безусловно, но это не в эту задачу. У нас есть GridConfig, в котором пользователь сам может настроить видимое количество строк. Я могу дописать этот виджет так, что он будет конфигурить все гриды по какому-то конфигу. Но потом, пока выпиливаем ручками.

**Comment by pozitronik** [comment]
>     2. В vendor/pozitronik/yii2-references/src/widgets - js/вью написаны на bs3, добавить bs4.

Некритично: js написаны с поддержкой fa, и не конфликтуют (ошибки были из-за использования bs3-модалок).

**Comment by pozitronik** [comment]
Готово.
