### ISSUE TITLE
Нет правила обработки для страницы смены пароля

### ISSUE THREAD

**Issue by s1lver** [cusodede/dpl#262]
При редиректе на страницу смены пароля получаем сообщение "404. Страница не найдена"

**Comment by pozitronik** [comment]
Как воспроизвести? По шагам.

**Comment by s1lver** [comment]
1) Заходим на страницу "Пользователи"
2) Нажимаем сменить пароль у  пользователя
3) Авторизовываемся под этим пользователям
4) Редирект на страницу смены пароля
