### ISSUE TITLE
Переключение на identity

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#27]
Нужно сделать возможность переключаться на identity любого другого пользователя (при наличии соответствующего права), с возможностью переключаться обратно.
Действия под "переключённым" пользюком должны логироваться, т.е. в History::$delegate должен попадать id оригинального юзера.

**Comment by pozitronik** [comment]
альзо, ты забыл про
>
>в History::$delegate должен попадать id оригинального юзера.

Добавлю сам.

**Comment by artemvolt** [comment]
> альзо, ты забыл про
> 
> > в History::$delegate должен попадать id оригинального юзера.
> 
> Добавлю сам.

Я это сделал )

**Comment by artemvolt** [comment]
> альзо, ты забыл про
> 
> > в History::$delegate должен попадать id оригинального юзера.
> 
> Добавлю сам.

Не знаю, что в pr было изменено, но изменение делегейт пропало.

**Comment by pozitronik** [comment]
да? ну мог проморгать, сорян

**Comment by pozitronik** [comment]
А что произойдёт, если локально поправить куку?

**Comment by artemvolt** [comment]
> А что произойдёт, если локально поправить куку?

Если ты имеешь ввиду в браузере, то значение куки шифруется ключом из конфига. Скорей всего ты повредишь значение и с большей долей вероятности, при привидении к инту, будет 0 и вылетит ошибка.
