### ISSUE TITLE
Добавить хлебные крошки

### ISSUE THREAD

**Issue by pepebotika69** [cusodede/dpl#29]
![Screenshot from 2021-05-25 15-35-05](https://user-images.githubusercontent.com/14938095/119498907-d0ad4280-bd6e-11eb-9077-025b07230156.png)

**Comment by pozitronik** [comment]
Тут и $title не хватает.
У меня где-то был код, генерящий и то и другое по дефолту, для прототипов его надо будет поставить.

**Comment by pepebotika69** [comment]
я нашел стандартный способ в views/db/process-list.php:
$this->title = 'Мониторинг процессов БД ';
$this->params['breadcrumbs'][] = $this->title;

ты это имел в виду?

**Comment by pozitronik** [comment]
Нет, я имел в виду, что навигация и заголовок генерируются (начерно, естественно) контроллером.

**Comment by pozitronik** [comment]
https://github.com/cusodede/bc/commit/72652df02c2e7453f98a1b398067b59610714bb0
