### ISSUE TITLE
Новая логика инициации начислений

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#296]
1. DOL присылает нам данные о заключённых договорах (via RabbitMQ, реализовано).
2. Мы по API ходим в DOL и дообогащаем эти данные. Нам нужны SOC карт в этом договоре + телефонный номер продавца. Вроде как готово.
2.1. Почему не получать эти данные сразу из очереди? Для компактности сообщений? Изначально такого вопроса не было, потому что обогащать требовалось не все договора.
2.2. В одном договоре может быть произвольное количество сим-карт. Бонус платится за каждую.
3. После обогащения проверяется, попадает ли проданный договор под правило начисления.
3.1. Это можно делать до обогащения - и если правило не найдено, то обогащения не производить. Т.о. это снимает вопрос по п. 2.1.
3.2. Правила начисления сейчас работают "от тарифа", уточняя условия "вниз", от дилера до ТТ. Т.о., если конкретное правило по дилеру (и ниже) не найдено, будет применено общее правило начисления по тарифу. Нужно добавить логику "игнорирования" определённых дилеров, для которых вознаграждения не применяются в принципе.
4. Договора, попавшие под правила, инициируют запуск расчёта вознаграждений (то, что сейчас пускается от продаж). Расчёты идут тем же макаром, что сейчас (очереди в фоне, etc), полученные вознаграждения подвязываются к договорам, как бы их обогащая (эта подвязка чисто информационная).
5. В договоре есть телефон продавца, оформившего продажу. На УЗ продавца в DPL падают вознаграждения, полученные в п. 4.
5.1. Если в DPL нет УЗ продавца с таким телефоном - она создаётся стандартным и уже готовым способом. Цель этого: когда продавец авторизуется, то увидит бонусы по всем своим продажам и (после подтверждения) сможет их вывести.

**Comment by s1lver** [comment]
> 2.1. Почему не получать эти данные сразу из очереди? Для компактности сообщений? Изначально такого вопроса не было, потому что обогащать требовалось не все договора.
Да. События в очереди должны быть маленькими, раздувать очень плохо.

> 3.1. Это можно делать до обогащения - и если правило не найдено, то обогащения не производить. Т.о. это снимает вопрос по п. 2.1.
Нам приходят вообще все события по договору. Реагировать надо только на финализацию договора. Следовательно, проводить проверки надо тоже по этому принципу.

**Comment by pozitronik** [comment]
> Нам приходят вообще все события по договору. Реагировать надо только на финализацию договора. Следовательно, проводить проверки надо тоже по этому принципу.

Принято.

**Comment by pozitronik** [comment]
> В одном договоре может быть произвольное количество сим-карт. Бонус платится за каждую.

Если появляется признак «Семья» -  то в данном случае платим за 1 симкарту (главную первую) с отдельным правилом начисления бонусов. за телефонные номера в пакете семья не платим.

**Comment by s1lver** [comment]
> > В одном договоре может быть произвольное количество сим-карт. Бонус платится за каждую.
> 
> Если появляется признак «Семья» - то в данном случае платим за 1 симкарту (главную первую) с отдельным правилом начисления бонусов. за телефонные номера в пакете семья не платим.

А мы этот признак берем или нет? Сейчас мы этот признак не тянем. Может добавим его сразу?

**Comment by pozitronik** [comment]
> 
> А мы этот признак берем или нет? Сейчас мы этот признак не тянем. Может добавим его сразу?

Постараюсь не забыть. Но для MVP не нужно, если забуду - всплывёт само.

**Comment by pozitronik** [comment]
**Осталось доделать:** нужно добавить логику "игнорирования" определённых дилеров, для которых вознаграждения не применяются в принципе.

**Comment by pozitronik** [comment]
1. Проверить сценарии создания пользователя и селлера - сейчас требует email при создании, хотя не должно.
2. Мы можем создавать вознаграждения без пользователей. Они привязываются к контракту, и никому не начисляются.
