### ISSUE TITLE
Процесс регистрации продавцов

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#31]
Реализовать по ТЗ, пока только со стороны бэкэнда + админский интерфейс, т.е. +/- сценарий "продавец пришёл к дилеру и хочет принять участие в мотивационной программе".
Нужны все описанные структуры и процессы, где непонятно или пока нет возможности (например, валидация данных во внешних сервисах) - оставлять заглушки.
Не забыть про логирование через HistoryModule.
Сканы анкет хранить через FileStorageModule.

**Comment by pepebotika69** [comment]
Нужно статусы добавить в status_rules.php

**Comment by pozitronik** [comment]
Валидация данных (проверки паспорта, инн, снилса) не должны препятствовать регистрации. Мы должны сохранить корректно введённые данные, делая эти проверки отдельным процессом/процессами.

**Comment by pozitronik** [comment]
Сущность продавца должна стыковаться с сущностью пользователя. При регистрации продавца нужно создавать пользователя, под которым он будет ходить; логин/почта должны храниться именно у пользователя.

Пароль пользователю делаем дефолтный, флаг is_pwd_outdated=true, на почту кидаем ссылку для входа и смены пароля.

**Comment by pozitronik** [comment]
Работу с загрузками переделать, использовать методы uploadAttribute()/files();
