### ISSUE TITLE
Проработка и заполнение ролевой модели

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#5]
По данным из БТ внести в систему все указанные доступы (с соответствующим осмыслением).
Доступы сгруппировать по ролям, как указано в БТ.

Попутно:
1) Проверить интерфейс управления ролями;
2) Работоспособность ролевой модели;
3) Подумать над улучшениями, если что-то реализуется быстро - сделать, если не быстро - оставить todo.

**Comment by pepebotika69** [comment]
##В разрешений и в группах разрешений
1. количество записей неправильно считается (левый верхный угол)
2. В Конфигурации Максимальное количество записей на одной странице (0 - без ограничения) не работает. Как-то сам виджет выбирает сколько когда показывать.
3. В Конфигурации Максимальное количество записей на одной странице (0 - без ограничения) Label неправильный - типа без ограничения, а на самом деле ограничения 20
3. плавающий заголовок - не удается проверить потому-что виджет никогда не выводит больше 17 записей
4. пагинация не работает. точнее криво работает. Переводит в след страницу но количество записей рандомно, да и записи могут повториться.
5. Как  удалять записи?
6. Когда много пермисии, нужен поиск по пермисиям(в модульном окне)

**Comment by pepebotika69** [comment]
1, 2 и 5  - понял в чем дело. запрос возвращает правильное количество записей, но Грид рисует их пачками.
Все эти 7 записи с ИД 4 будут одна строка.
![Screenshot from 2021-05-13 15-56-30](https://user-images.githubusercontent.com/14938095/118128670-e2542900-b403-11eb-8282-b5294eb05709.png)

**Comment by pepebotika69** [comment]
по 4 сделаю ПР

**Comment by pepebotika69** [comment]
3 пункт поправил отдельным ПР на виджет.
https://github.com/pozitronik/yii2-grid-config/pull/2
