### ISSUE TITLE
Фильтрация для AJAX запросов

### ISSUE THREAD

**Issue by pepebotika69** [cusodede/dpl#51]
например: если мы менеджеры магазина А, и ищем продавца, то в живом поиске должен получить только продавцов магазина А. 

Это же фильтрация должна быть по всем моднлям где оно уместно

**Comment by pozitronik** [comment]
Думаю, лучше всего это сделать через области видимостей, привязанные к правам доступа, и реализованные через ActiveQuery. А-ля:
```php
$query = SomeModel::find()->where(...)->scope(SomeModel::class)->...
```
вызов ```scope()```, определённый где-нибудь в ActiveQueryTrait(), будет вызывать функцию ```SomeModel::scope(ActiveQuery $query)```, а в той уже будут прописаны все условия, генерирующие условия области видимости запроса.

@pepebotika69, что думаешь?
