### ISSUE TITLE
Интеграция с http://recogdol.beelinetst.ru

### ISSUE THREAD

**Issue by pepebotika69** [cusodede/dpl#60]
1. Интегрироваться с http://recogdol.beelinetst.ru/
2. Отправить запрос на распознование паспорта
3. Заполнить паспортные данные с данными из http://recogdol.beelinetst.ru/

Основная задача: #31

**Comment by pozitronik** [comment]
[Конфиг](https://github.com/cusodede/dpl/blob/40cb697e7cf8ef58782926b8db083d3495020da7/modules/recogdol/config/config.php#L1) модуля должен быть в общем конфиге приложения.

**Comment by pepebotika69** [comment]
@pozitronik зачем? таким образом у нас общий конфиг будет огромный.
1. Yii2 дает возможность создавать конфиги для каждого модуля, наверно это не зря. Модуль это штука которая может жить сама по себе, со своим конфигом в том числе.
2. Общий конфиг будет со временем огромный
3. В ЛК было сделано круто: в общий конфиг подключаем все модули которые нужны. А внутри каждого модуля уже создаем свой конфиг. К тому же бывает внутри модуля нужно создавать еще модуль, вот и прекрасно, для него тоже будет свой конфиг.
